# Generated by Django 5.2.17 on 2026-09-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_profile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seo_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
