# Generated by Django 5.2.17 on 2026-09-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_seo_keywords_alter_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='skills',
        ),
    ]
